export const GET_MOVIES_CONFIG = "GET_MOVIES_CONFIG";
export const GET_RECOMMENDED_MOVIES = "GET_RECOMMENDED_MOVIES";
export const GET_RECOMMENDED_SERIES = "GET_RECOMMENDED_SERIES";
export const GET_MOVIE_RESULTS = "GET_MOVIE_RESULTS";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
